apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  domain: 192.168.59.100
  port: "80"
  backend_url: blog-api-service.default.svc.cluster.local:8080
  cert_name: "192.168.59.100.pem"
  cert_key_name: "192.168.59.100-key.pem"