"""Alter table Post. Alter column 'tags': change data type from String to Array.

Revision ID: 4b65546e1ace
Revises: a247b82d042e
Create Date: 2024-02-13 12:56:28.177786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b65546e1ace'
down_revision: Union[str, None] = 'a247b82d042e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'tags',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.ARRAY(sa.String(length=30)),
               existing_nullable=False)
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('posts', 'tags',
               existing_type=sa.ARRAY(sa.String(length=30)),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
