apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pg-data
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage