apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage
spec:
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage