apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-blog-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-blog-deployment
  template:
    metadata:
      labels:
        app: fastapi-blog-deployment
    spec:
      containers:
      - name: fastapi-blog-deployment
        image: sergeyvernyk/blog_fastapi:0.1.3
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fastapi-secrets
        volumeMounts:
        - name: blog-api-volume-static
          mountPath: /vol/static
      volumes:
      - name: blog-api-volume-static 
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: blog-api-service
spec:
  selector:
    app: fastapi-blog-deployment
  ports:
  - port: 8080
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer