apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-db-deployment
spec:
  selector:
    matchLabels:
      app: postgresql-db-deployment
  template:
    metadata:
      labels:
        app: postgresql-db-deployment
    spec:
      containers:
      - name: postgresql-db-deployment
        image: postgres:14.6-alpine
        resources:
          limits:
            memory: "512Mi"
            cpu: "150m"
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secrets
        volumeMounts:
        - name: postgres-pg-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pg-data
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  selector:
    app: postgresql-db-deployment
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
