apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: sergeyvernyk/nginx_blog:1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: blog-api-ssl-certs
          mountPath: /vol/certs
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: domain
        - name: API_VERSION
          valueFrom:
            secretKeyRef:
              name: fastapi-secrets
              key: API_VERSION
        - name: PORT
          valueFrom:
            configMapKeyRef: 
              name: nginx-config
              key: port
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: backend_url
        - name: CERT_NAME
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: cert_name
        - name: CERT_KEY_NAME
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: cert_key_name
      volumes:
      - name: blog-api-ssl-certs
        persistentVolumeClaim:
          claimName: blog-api-ssl-certs
  replicas: 2  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-deployment
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
  type: LoadBalancer