name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches:
      - master


jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          # only changed files will be analyzed in PR
          args: --apply-fixes
          # analyze ONLY changed files in a pull request
          pr-mode: false
          # create a new branch with fixes and create a pull request to the original branch
          push-fixes: pull-request
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
